-- name: UpsertServer :one
-- Find a server by hostname and environment, or create it.
-- TODO: Server.name currently defaults to hostname. A custom display name
-- will be supported in a later version.
INSERT INTO servers (name, hostname, environment, status)
VALUES (
    sqlc.arg('hostname'),
    sqlc.arg('hostname'),
    sqlc.arg('environment'),
    'unknown'
)
ON CONFLICT (hostname, environment)
DO UPDATE SET updated_at = now()
RETURNING id;

-- name: CreateAgent :one
-- Insert a new agent linked to an existing server.
-- The agent id is generated by the database. signing_key is the per-agent
-- HMAC key issued at registration and used to verify signed requests.
INSERT INTO agents (server_id, secret, version, signing_key)
VALUES (
    sqlc.arg('server_id'),
    sqlc.arg('secret'),
    sqlc.arg('version'),
    sqlc.arg('signing_key')
)
RETURNING id, status;
